import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"Shona_iz_Bot") 
SUDO=os.environ.get("SUDO",None)
BOT_NAME = os.environ.get("BOT_NAME","Shona Ai")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/e7f158bef8d795c823870.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CdauxWQACAmtkHdVipVVexTejJ9fgUKf_WllxNgACKwMAAt_U8UTylneQIu4aSy8E")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL",None)
OWNER_USERNAME = os.environ.get("OWNER_USERNAME","Hyper_x_Rachit")
SUDO=os.environ.get("SUDO",None)
SUPPORT_GRP = os.environ.get("SUPPORT_GRP",None)
