import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"Nothing_ChatGpt_bot") 
SUDO=os.environ.get("SUDO","5339377884")
BOT_NAME = os.environ.get("BOT_NAME","CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/9fa2101b77407dbec7d31.jpg")
STKR = os.environ.get("STKR","CAACAgEAAxkBAAIBZmSdjTwRxnmJHNSK6XtHdRBBd6TnAAI3BAAC-PJRRHTyvLpb7OWZLwQ")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","Nothingbotz")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","Infinityuncounted01")
SUDO=os.environ.get("SUDO","5339377884")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","Nothingbots")
